name: Codespell

# Always run on Pull Requests
on:
  pull_request:

jobs:
  pylint:
    name: Run Codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run check
        uses: codespell-project/actions-codespell@master
